services:
  db:
    container_name: donut_factory_container
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-donuts}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-donuts_pass}
      POSTGRES_DB: ${POSTGRES_DB:-donuts_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: donuts_pgdata
